global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
        - "localhost:9090"
  - job_name: avail_node
    scrape_interval: 5s
    static_configs:
      - targets:
        - "node:9615"
  - job_name: node
    static_configs:
      - targets:
        - "node_exporter:9100"
